### ISSUE TITLE
Could use HWND instead of void* for window handles.

### ISSUE THREAD

**Issue by nofishonfriday** [juliansader/ReaExtensions#11]
Reaper API support dealing with HWNDs I think, so why not pass / retrieve HWND instead of void* when it's actually a window handle?
e.g.
JS_Window_Find() etc. 
Could provide for a bit more type safety maybe.

More a cosmetic thing than an actually issue so feel free to close. :)

**Comment by juliansader** [comment]
I would definitely like to use HWNDs instead of void*, but unfortunately I couldn't get it to work:
https://forum.cockos.com/showthread.php?p=2025420

Do you know of a better way to do it?

**Comment by nofishonfriday** [comment]
Oh missed that thread. Ok, seems pretty clear it's not possible currently (I don't know of anything else either)..
Thanks. Closing.
